// Real, downloadable PDF version of the signed maid contract (CEO 2026-09-23).
//
// SERVER-ONLY — never import this from a "use client" component. Two reasons:
//   1. @react-pdf/renderer's browser build fetches remote images (ID card /
//      selfie / signature, all on R2's public `*.r2.dev` domain) via fetch(),
//      which the site's CSP connect-src blocks (only allows
//      *.r2.cloudflarestorage.com, not *.r2.dev — see lib/supabase/proxy.ts).
//      Server-side Node fetch has no CSP at all, so rendering here sidesteps
//      the whole problem instead of loosening a site-wide security header.
//   2. Keeps react-pdf's fairly heavy dependency tree out of the client bundle
//      entirely — this document is generated by the API route in
//      app/api/chairops/contract/pdf/route.ts and streamed down as a file.
//
// This is a PARALLEL implementation of contract-document.tsx (the on-screen
// HTML preview) — @react-pdf/renderer uses its own View/Text/Image primitives,
// not DOM/CSS, so the JSX can't be shared. Keep the Thai wording of both IN
// SYNC BY HAND whenever either changes.

import { Document, Page, View, Text, Image, Font, StyleSheet } from "@react-pdf/renderer";
import type { ContractDocData, ContractSignature } from "./types";

const SITE_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://pooilgroup.vercel.app";

let fontsRegistered = false;
/** Self-hosted TTF served from our own /public (not @fontsource — that ships
 *  woff/woff2 only, which silently produced a blank page in testing; fontkit
 *  needs real ttf/otf). Fetched over plain HTTPS from our own domain, so it
 *  works identically in local dev and on Vercel with zero serverless
 *  filesystem-bundling risk (no fs.readFileSync of a `public/` path, whose
 *  presence in the deployed function bundle is not guaranteed). */
function ensureFonts() {
  if (fontsRegistered) return;
  Font.register({
    family: "IBMPlexSansThai",
    fonts: [
      { src: `${SITE_URL}/fonts/ibm-plex-sans-thai-regular.ttf`, fontWeight: 400 },
      { src: `${SITE_URL}/fonts/ibm-plex-sans-thai-bold.ttf`, fontWeight: 700 },
    ],
  });
  fontsRegistered = true;
}

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontFamily: "IBMPlexSansThai",
    fontSize: 10.5,
    lineHeight: 1.5,
    color: "#18181b",
  },
  headerRow: { flexDirection: "row", alignItems: "flex-start", marginBottom: 4 },
  headerSpacer: { width: 70 },
  title: { flex: 1, textAlign: "center", fontSize: 14, fontWeight: 700 },
  photoBox: {
    width: 70,
    height: 90,
    borderWidth: 1,
    borderColor: "#a1a1aa",
    borderStyle: "solid",
    alignItems: "center",
    justifyContent: "center",
  },
  photoPlaceholder: { fontSize: 7, color: "#a1a1aa", textAlign: "center" },
  photoImg: { width: 70, height: 90, objectFit: "cover" },
  p: { marginTop: 3 },
  underline: { textDecoration: "underline" },
  sectionTitle: { marginTop: 12, fontSize: 11, fontWeight: 700 },
  sectionBody: { marginTop: 3 },
  listItem: { flexDirection: "row", marginTop: 2 },
  listBullet: { width: 14 },
  listText: { flex: 1 },
  muted: { color: "#52525b" },
  signRow: { flexDirection: "row", gap: 12, marginTop: 8 },
  signBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d4d4d8",
    borderStyle: "solid",
    padding: 8,
    alignItems: "center",
  },
  signRole: { fontSize: 10.5, fontWeight: 700 },
  signImgWrap: { height: 46, marginTop: 6, alignItems: "center", justifyContent: "flex-end" },
  signImg: { maxHeight: 46, maxWidth: 140 },
  signPlaceholder: { fontSize: 8, color: "#a1a1aa" },
  signName: {
    marginTop: 4,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: "#d4d4d8",
    borderTopStyle: "solid",
    fontSize: 9,
  },
  signDate: { fontSize: 8, color: "#a1a1aa" },
  idCardImg: { marginTop: 4, maxHeight: 160, maxWidth: 260, objectFit: "contain" },
  hashBox: {
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#d4d4d8",
    borderStyle: "solid",
    padding: 8,
    fontSize: 8,
    color: "#71717a",
  },
  hashMono: { fontFamily: "Courier" },
});

function fill(v: string | null | undefined, dots = "........................"): string {
  const t = (v ?? "").toString().trim();
  return t === "" ? dots : t;
}

function bahtOrDots(n: number | null): string {
  return n == null ? "......................" : n.toLocaleString("th-TH");
}

function thaiDate(iso: string | null): string {
  if (!iso) return "____/____/______";
  const d = new Date(`${iso}T00:00:00+07:00`);
  return new Intl.DateTimeFormat("th-TH", {
    timeZone: "Asia/Bangkok",
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(d);
}

function thaiDateTime(iso: string): string {
  const d = new Date(iso);
  return new Intl.DateTimeFormat("th-TH", {
    timeZone: "Asia/Bangkok",
    dateStyle: "long",
    timeStyle: "short",
  }).format(d);
}

export function ContractPdfDocument({
  data,
  signature,
}: {
  data: ContractDocData;
  signature?: ContractSignature | null;
}) {
  ensureFonts();

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerRow}>
          <View style={styles.headerSpacer} />
          <Text style={styles.title}>สัญญาจ้างเหมาทำความสะอาดและเก็บเงินนำส่งธนาคาร</Text>
          <View style={styles.photoBox}>
            {data.selfieImageUrl ? (
              <Image src={data.selfieImageUrl} style={styles.photoImg} />
            ) : (
              <Text style={styles.photoPlaceholder}>ติดรูปถ่าย</Text>
            )}
          </View>
        </View>

        <Text style={styles.p}>คู่สัญญา</Text>
        <Text style={styles.p}>
          1. บริษัท เจพีซิงค์กรุ๊ป จำกัด ซึ่งต่อไปในสัญญานี้จะเรียกว่า “ผู้ว่าจ้าง”
        </Text>
        <Text style={styles.p}>
          2. ชื่อ <Text style={styles.underline}>{fill(data.maidName)}</Text> ซึ่งต่อไปในสัญญานี้จะเรียกว่า “ผู้รับจ้าง”
        </Text>
        <Text style={styles.p}>
          เลขบัตรประชาชน: <Text style={styles.underline}>{fill(data.idCardNumber)}</Text>{"   "}
          เบอร์โทร: <Text style={styles.underline}>{fill(data.phone, "..............")}</Text>
        </Text>
        <Text style={styles.p}>
          ที่อยู่: <Text style={styles.underline}>{fill(data.address, "....................................................................")}</Text>
        </Text>

        <Text style={styles.sectionTitle}>ข้อ 1 ลักษณะงาน</Text>
        <View style={styles.sectionBody}>
          {[
            "ทำความสะอาดพื้นที่และภายในบริเวณของบริษัทในช่วงเช้า",
            "ถูและทำความสะอาดบริเวณที่กำหนด พร้อมจัดเก็บให้เรียบร้อย",
            "เก็บเงินจากลูกค้าตามจุดที่กำหนด",
            "นำเงินทั้งหมดฝากเข้าบัญชีบริษัทภายในวันเดียวกัน",
            "ส่งหลักฐานการฝากเงิน (สลิป) และถ่ายรูปส่งให้ผู้ว่าจ้างทุกวัน",
          ].map((t, i) => (
            <View key={i} style={styles.listItem}>
              <Text style={styles.listBullet}>{i + 1}.</Text>
              <Text style={styles.listText}>{t}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.sectionTitle}>ข้อ 2 ค่าจ้างและการชำระเงิน</Text>
        <View style={styles.sectionBody}>
          <Text style={styles.p}>
            1. ผู้ว่าจ้างตกลงจ่ายค่าจ้างให้แก่ผู้รับจ้างเป็นจำนวนเงิน (
            <Text style={styles.underline}>{bahtOrDots(data.monthlyWage)}</Text> บาท) ต่อเดือน
          </Text>
          <Text style={styles.p}>
            2. ผู้ว่าจ้างจะโอนเงินเข้าบัญชีของผู้รับจ้างดังนี้ ชื่อบัญชี:{" "}
            <Text style={styles.underline}>{fill(data.salaryAccountName)}</Text> ธนาคาร:{" "}
            <Text style={styles.underline}>{fill(data.salaryBankName, "................")}</Text>
          </Text>
          <Text style={styles.p}>
            - เลขที่บัญชี: <Text style={styles.underline}>{fill(data.salaryAccountNo, "............................")}</Text>{" "}
            โอนภายในวันที่ <Text style={styles.underline}>{fill(data.payDayOfMonth?.toString() ?? null, "......")}</Text> ของทุกเดือน
          </Text>
          <Text style={styles.p}>3. ผู้รับจ้างต้องนำเงินที่เก็บได้ฝากเข้าบัญชีของบริษัทตามรายละเอียดดังนี้</Text>
          <Text style={styles.p}>
            - ชื่อบัญชี: <Text style={styles.underline}>{fill(data.companyAccountName ?? "บริษัท เจพีซิงค์กรุ๊ป จำกัด")}</Text> ธนาคาร:{" "}
            <Text style={styles.underline}>{fill(data.companyBankName, "................")}</Text>
          </Text>
          <Text style={styles.p}>
            - เลขที่บัญชี: <Text style={styles.underline}>{fill(data.companyAccountNo, "............................")}</Text> ประเภทบัญชี:{" "}
            <Text style={styles.underline}>{fill(data.companyAccountType, "ออมทรัพย์ / กระแสรายวัน")}</Text>
          </Text>
          <Text style={[styles.p, styles.muted]}>
            หากผู้รับจ้างไม่นำเงินส่งหรือมีการทุจริต บริษัทมีสิทธิบอกเลิกสัญญาทันที
          </Text>
        </View>

        <Text style={styles.sectionTitle}>ข้อ 3 ความรับผิดชอบ</Text>
        <View style={styles.sectionBody}>
          {[
            "ผู้รับจ้างต้องรับผิดชอบเงินที่เก็บได้ทั้งหมด",
            "หากเงินสูญหายหรือใช้ผิดวัตถุประสงค์ ต้องชดใช้เต็มจำนวน",
            "ห้ามนำเงินไปใช้ส่วนตัวก่อนนำฝากโดยเด็ดขาด",
            "หากตรวจพบการทุจริต บริษัทมีสิทธิบอกเลิกสัญญาและดำเนินการทางกฎหมายทันที",
          ].map((t, i) => (
            <View key={i} style={styles.listItem}>
              <Text style={styles.listBullet}>{i + 1}.</Text>
              <Text style={styles.listText}>{t}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.sectionTitle}>ข้อ 4 ระยะเวลาสัญญา</Text>
        <View style={styles.sectionBody}>
          <Text style={styles.p}>
            สัญญาฉบับนี้มีผลตั้งแต่วันที่ <Text style={styles.underline}>{thaiDate(data.startDate)}</Text> ถึงวันที่{" "}
            <Text style={styles.underline}>{thaiDate(data.endDate)}</Text>
          </Text>
          <Text style={[styles.p, styles.muted]}>
            เมื่อครบกำหนด หากไม่มีการบอกเลิกสัญญา สัญญานี้จะขยายออกไปโดยอัตโนมัติครั้งละ 1 เดือน
          </Text>
        </View>

        <Text style={styles.sectionTitle}>ข้อ 5 การลงนาม</Text>
        <Text style={[styles.sectionBody, styles.muted]}>
          คู่สัญญาทั้งสองฝ่ายได้อ่านและเข้าใจข้อความในสัญญาฉบับนี้โดยละเอียดแล้ว จึงได้ลงลายมือชื่อไว้เป็นหลักฐาน
        </Text>
        <View style={styles.signRow} wrap={false}>
          <View style={styles.signBox}>
            <Text style={styles.signRole}>ผู้ว่าจ้าง</Text>
            <View style={styles.signImgWrap}>
              <Text style={styles.signPlaceholder}>(อนุมัติล่วงหน้าโดยบริษัท)</Text>
            </View>
            <Text style={styles.signName}>(บริษัท เจพีซิงค์กรุ๊ป จำกัด)</Text>
            <Text style={styles.signDate}>วันที่ ____/____/______</Text>
          </View>
          <View style={styles.signBox}>
            <Text style={styles.signRole}>ผู้รับจ้าง</Text>
            <View style={styles.signImgWrap}>
              {signature?.signatureImageUrl ? (
                <Image src={signature.signatureImageUrl} style={styles.signImg} />
              ) : (
                <Text style={styles.signPlaceholder}>ลงชื่อ ____________________</Text>
              )}
            </View>
            <Text style={styles.signName}>({fill(data.maidName, "..............................")})</Text>
            <Text style={styles.signDate}>
              {signature?.signedAt ? `วันที่ ${thaiDate(signature.signedAt.slice(0, 10))}` : "วันที่ ____/____/______"}
            </Text>
          </View>
        </View>

        {data.idCardImageUrl && (
          <View style={{ marginTop: 12 }} wrap={false}>
            <Text style={styles.sectionTitle}>เอกสารแนบ · สำเนาบัตรประชาชน</Text>
            <Image src={data.idCardImageUrl} style={styles.idCardImg} />
          </View>
        )}

        {signature?.contentHash && (
          <View style={styles.hashBox} wrap={false}>
            <Text style={{ fontWeight: 700, color: "#52525b" }}>หลักฐานการลงนามอิเล็กทรอนิกส์</Text>
            <Text style={{ marginTop: 3 }}>
              ลงนามโดย {fill(signature.signedName, "-")}
              {signature.signedAt ? ` · ${thaiDateTime(signature.signedAt)}` : ""}
              {signature.signedIp ? ` · IP ${signature.signedIp}` : ""}
            </Text>
            <Text style={{ marginTop: 2 }}>
              รหัสตรวจสอบเอกสาร (SHA-256): <Text style={styles.hashMono}>{signature.contentHash}</Text>
            </Text>
            <Text style={{ marginTop: 2 }}>
              เอกสารนี้ลงลายมือชื่อทางอิเล็กทรอนิกส์ตาม พ.ร.บ. ว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์ พ.ศ. 2544 —
              รหัสตรวจสอบด้านบนผูกกับเนื้อหาสัญญา หากถูกแก้ไขภายหลังรหัสจะไม่ตรง.
            </Text>
          </View>
        )}
      </Page>
    </Document>
  );
}
